#Range: 0 ~ 10000
distance_DURABILITY = 500
#Range: -10000 ~ 10000
area_REMOVE_EXPERIENCE = -55
#Range: 0 ~ 10000
area_SPEED_AMPLIFIER = 0
#Range: 1.0 ~ 10000.0
distance_DAMAGE = 8.0
#Range: 0 ~ 10000
area_DURABILITY = 350
#Range: -10000 ~ 10000
distance_REMOVE_EXPERIENCE = -55
#Range: 1.0 ~ 10000.0
area_Damage = 12.0
#Range: 0 ~ 10000
area_SPEED_DURATION = 30
both_in_cooldown = true
#Range: 0 ~ 10000
distance_COOLDOWN = 200
#Range: 0 ~ 10000
area_EXPERIENCE_LEVEL = 5
#Range: 0 ~ 10000
area_cooldown = 300
#Range: 1.0 ~ 10000.0
area_RADIUS = 3.5
#Range: 0 ~ 10000
distance_EXPERIENCE_LEVEL = 5
#Range: 1 ~ 10000
distance_USE_TIME = 10
#Range: 0 ~ 10000
distance_DISTANCE = 16
